# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Literonim
tagline:          The Jekyll Butler
url:              http://getpoole.com
baseurl:          /Cwiczenia.Programowanie
pages_list:       
  About: "{{ site.baseurl }}/about"
  Archive: "{{ site.baseurl }}/archive"
paginate:         1

