# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Literonim
tagline:          The Jekyll Butler
url:              http://getpoole.com
pages_list:       
  About: '/Cwiczenia.Programowanie/about'
  Archive: '/Cwiczenia.Programowanie/archive'
paginate:         1
baseurl:          /

